version: "3.8"

services:
  streamlit:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
    environment:
      - STREAMLIT_ENV=local

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/  # Use correct storage path
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - streamlit
    
volumes:
  chroma-data:
    driver: local
