apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: your_dockerhub_account/streamlit-app:latest  # Replace with your image
          ports:
            - containerPort: 8501
          env:
            - name: STREAMLIT_ENV
              value: "local"
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: streamlit-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  selector:
    app: streamlit
  ports:
    - port: 80
      targetPort: 8501
  type: LoadBalancer
