name: Backup & Upload ChromaDB Data

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  backup-chroma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Save ChromaDB Data as Tarball
        run: |
          tar -czf chroma_backup.tar.gz -C ./chroma-data .
          mkdir -p chroma_data_backup
          mv chroma_backup.tar.gz chroma_data_backup/

      - name: Upload Backup as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chroma-db-backup
          path: chroma_data_backup/chroma_backup.tar.gz
